# Spring properties
spring:
  application:
     name: edge-service     # Service registers under this name
  freemarker:
    enabled: true           # Ignore Eureka dashboard FreeMarker templates
  oauth2:
    sso:
      home:
        secure: false
        path: /,/**/*.html
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      userInfoUri: http://localhost:9999/uaa/user

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
  user:
    path: /user/**
    url: http://localhost:9999/uaa/user

zuul:
  routes:
    web-service: /**
    registration-service: /eureka/**


security:
  user:
    password: password

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}} # unique ID
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION