# Spring properties
spring:
  application:
     name: user-service  # Service registers under this name
  freemarker:
    enabled: true        # Ignore Eureka dashboard FreeMarker templates


# HTTP Server
server:
  port: 8102   # HTTP (Tomcat) port

# Discovery Server Access
#  1. Define URL of registrationservice server (defaultZone)
#  2. Give the process a unique instance id - allows multiple instances on SAME host
#     NOTE-1: spring.application.instance_id is only set when run on Cloud Foundry,
#             so we fallback on the server-port when it is not defined
#     NOTE-2: Syntax ${x:${y}} = use $x if set, otherwise use $y
#  3. Reduce lease-renewal time so processes register more quickly
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}} # unique ID
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION



