# Spring properties
spring:
  application:
    name: web-service  # Identify this application
    host: springbox-config-server-${random-word}
  freemarker:
    enabled: false     # Ignore Eureka dashboard FreeMarker templates
  thymeleaf:
    cache: false       # Allow Thymeleaf templates to be reloaded at runtime
    prefix: classpath:/web-server/templates/    # Template location for this application only
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/user

# Map the error path to error template (for Thymeleaf)
error:
  path=/error

# Discovery Server Access
#  1. Define URL of registrationservice server (defaultZone)
#  2. Reduce lease-renewal time so processes register more quickly
eureka:
  instance:
     leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/

# HTTP Server
server:
  port: 8101   # HTTP (Tomcat) port
