# Spring properties
spring:
  application:
     name: edge-service     # Service registers under this name
  freemarker:
    enabled: true           # Ignore Eureka dashboard FreeMarker templates
#  oauth2:
#    sso:
#      home:
#        secure: false
#        path: /,/**/*.html
#    client:
#      accessTokenUri: http://localhost:9999/uaa/oauth/token
#      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
#      clientId: acme
#      clientSecret: acmesecret
#    resource:
#      userInfoUri: http://localhost:9999/uaa/user

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  routes:
    web-service: /**
    registration-service: /eureka/**
#  user:
#    path: /user/**
#    url: http://localhost:9999/uaa/user

# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9998/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}} # unique ID
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
